name: Crates

on: [release]

jobs:
  test:
    name: Test on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - run: ~/.cargo/bin/rustup self update
    - run: ~/.cargo/bin/rustup update
    - run: ~/.cargo/bin/cargo build --verbose
    - run: ~/.cargo/bin/cargo test --verbose
  publish:
    name: Publish to crates.io
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - run: ~/.cargo/bin/rustup self update
    - run: echo "${GITHUB_CONTEXT}"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - run: ~/.cargo/bin/cargo publish
      if: github.event_name == 'release' && github.event.action == 'published'
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

